name: Deploy Lambda via AWS CDK

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set Up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Step 3: Set Up AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 4: Install CDK & Dependencies
      - name: Install Dependencies
        run: |
          npm install -g aws-cdk
          cd cdk
          pip install -r requirements.txt

      # Step 5: CDK Bootstrap (if not already done)
      - name: CDK Bootstrap
        run: |
          cd cdk
          cdk bootstrap aws://918888467489/us-east-1 || echo "Bootstrap already exists"

      # Step 6: Deploy Stack
      - name: Deploy CDK Stack
        run: |
          cd cdk
          cdk deploy --require-approval never