name: Destroy CDK Stack

# Only runs manually
on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Step 3: Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 4: Install CDK & dependencies
      - name: Install Dependencies
        run: |
          npm install -g aws-cdk
          cd cdk
          pip install -r requirements.txt

      # Step 5: Destroy CDK Stack
      - name: Destroy Stack
        run: |
          cd cdk
          cdk destroy --force